### ISSUE TITLE
Not functioning with new ACF JavaScript API

### ISSUE THREAD

**Issue by gavin310** [yeah8000/acf-autosize#11]
I started getting a bunch of JavaScript errors. In acf-autosize.js I had to replace `add_action` with `addAction` and replace `$field.attr` with `$field.$el.attr` and `$field.hasClass` with `$field.$el.hasClass`.

**Comment by clausreiser** [comment]
Hey @gavin310, 

which version of acf are you using? I'm currently testing with 5.9.1 and everything seems to be working.

**Comment by clausreiser** [comment]
Don't know if there are still issues, but I just updated to the new API, integratung @gavin310 s suggested changes, so hopefully it's fixed now.
