### ISSUE TITLE
Make min-height filterable

### ISSUE THREAD

**Issue by hirasso** [yeah8000/acf-autosize#2]
Hi there, great little plugin! 👏

A suggestion: Would it be possbible to make the min-height for wysiwyg filterable? At the moment it’s `200px` hard coded:

```javascript
function editorAutoHeight (editor, minHeight = 200) {
  let height =
    $(editor.iframeElement)
      .contents()
      .find('html')
      .height() || minHeight
  height = height < minHeight ? minHeight : height
  $(editor.iframeElement).css('height', height)
}
```

cheers from Berlin 😉

**Comment by hirasso** [comment]
Added the feature in pull request #3

**Comment by clausreiser** [comment]
Hi there,

sorry that this took so long... Good idea! And already solved. Wonderful!

Thanks and all the best
