### ISSUE TITLE
TinyMCE broken fullscreen mode

### ISSUE THREAD

**Issue by timohubois** [yeah8000/acf-autosize#20]
Hi, there are two little bugs with the tinyMCE fullscreen mode:

1. Toolbar position
![Screenshot 2021-08-30 at 21 24 42](https://user-images.githubusercontent.com/46505685/131394050-74d49b0c-33af-4b21-93a9-d3fb77740cf2.jpg)

2. The plugin also destroys the height of the fullscreen wrapper there are any text changes and the plugin prevents to scroll inside tinyMCE fullscreen mode.

Is it possible to disable autosize at the tinyMCE fullscreen mode?

**Comment by clausreiser** [comment]
Hi @timohubois, 

thanks for the report. The bug got fixed in version 2.0.11. Could you please update and check it out? 

Regards

**Comment by timohubois** [comment]
@hoffmannclaus: It work like a charm. Great!
